#!/bin/sh

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

# install python versions using pyenv
. "$DIR/python_versions"

# create symlinks for dotfiles
ln -sv $DIR/.spacemacs $HOME/.spacemacs
