#!/bin/sh

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

 # Tell the shell where virtualenvs live
 mkdir -p $HOME/.virtualenvs
 export WORKON_HOME="$HOME/.virtualenvs"

 # Go and Gopath
 export PATH=$PATH:/usr/local/go/bin:$HOME/dev/bin
 export GOPATH=$HOME/dev

# upgrade pip
echo "Upgrading Pip..."
pip install --upgrade pip > /dev/null 2>&1

# install pew
echo "Installing pew..."
sudo pip install pew > /dev/null 2>&1

# install python versions using pew
echo "Installing Python 3.5.2..."
pew install 3.5.2 > /dev/null 2>&1
echo "Installing Python 2.7.12..."
pew install 2.7.12 > /dev/null 2>&1

# install cookiecutter
echo "Installing cookiecutter..."
pip install cookiecutter > /dev/null 2>&1

# create symlinks for dotfiles
ln -svf $DIR/.spacemacs $HOME/.spacemacs
ln -svf $DIR/.bashrc $HOME/.bashrc
ln -svf $DIR/.gitconfig $HOME/.gitconfig
ln -svf $DIR/.gitignore_global $HOME/.gitignore_global

# fetch Spacemacs Go layer requirements
go get -u -v github.com/nsf/gocode
go get -u -v github.com/rogpeppe/godef
go get -u -v golang.org/x/tools/cmd/oracle
go get -u -v golang.org/x/tools/cmd/gorename
